In [1]:
import pickle
from utils.analysis_from_interaction import *
from egg.core.language_analysis import Disent
from language_analysis_local import TopographicSimilarityConceptLevel, encode_target_concepts_for_topsim

# calculate metrics from stored interactions

In [2]:
datasets = ('(3,4)',)
n_attributes = (3,)
n_values = (4,)
n_epochs = 400
#paths = ['results/' + d + '_sample_scaling_10_balanced_False_vsf_3/' for d in datasets]
paths = [f'results/{d}_game_size_10_vsf_3/' for d in datasets]


In [3]:
context_unaware = False # whether original or context_unaware simulations are evaluated
length_cost = False
if context_unaware:
    setting = 'context_unaware'
elif length_cost:
    setting = 'length_cost_001'
else:
    setting = 'standard'

### entropy scores: MI, effectiveness, efficiency

In [10]:
for d in range(len(datasets)):
    for run in range(5):

        path_to_run = paths[d] + '/' + str(setting) +'/' + str(run) + '/' 
        print(path_to_run)
        path_to_interaction = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        interaction = torch.load(path_to_interaction)

        attributes = n_attributes[d]
        values = n_values[d]
        scores = information_scores(interaction, attributes, values, normalizer="arithmetic")

        pickle.dump(scores, open(path_to_run + 'entropy_scores.pkl', 'wb'))
    

results/(3,4)_game_size_10_vsf_3//standard/0/


c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:310: RuntimeWarning: invalid value encountered in divide
  normalized_MI_conc_x_cont = ((m_entropy_concept_x_context + c_entropy_concept_x_context - joint_entropy_concept_x_context)
c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:319: RuntimeWarning: invalid value encountered in divide
  normalized_effectiveness_conc_x_cont = ((joint_entropy_concept_x_context - m_entropy_concept_x_context)
c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:326: RuntimeWarning: invalid value encountered in divide
  normalized_consistency_conc_x_cont = (joint_entropy_concept_x_context - c_entropy_concept_x_context) / m_entropy_concept_x_context


results/(3,4)_game_size_10_vsf_3//standard/1/
results/(3,4)_game_size_10_vsf_3//standard/2/
results/(3,4)_game_size_10_vsf_3//standard/3/
results/(3,4)_game_size_10_vsf_3//standard/4/


###  message length

In [11]:
# we evaluated message length per hierarchy level after training but 
# you can also use the HierarchicalMessageLength callback and store the results 
# TODO: Message length results look weird, needs to be fixed!

for d in range(len(datasets)):
    
    for run in range(5): 
        
        path_to_run = paths[d] + '/' + str(setting) +'/' + str(run) + '/'
        path_to_interaction = (path_to_run + 'interactions/train/interactions_epoch' + str(n_epochs))
        path_to_interaction = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        interaction = torch.load(path_to_interaction)

        attributes = n_attributes[d]
        values = n_values[d]
        scores = message_length_per_hierarchy_level(interaction, attributes)
        
        pickle.dump(scores, open(path_to_run + 'message_length_hierarchical.pkl', 'wb'))

tensor([[ 9,  9,  9,  0],
        [ 8, 13, 14,  0],
        [ 8,  3, 11,  0],
        ...,
        [ 5,  5,  9,  0],
        [ 1, 10, 10,  0],
        [15, 12, 12,  0]])
tensor([1, 1, 1,  ..., 1, 1, 1])
message length tensor([3, 3, 3,  ..., 3, 3, 3])
tensor([[ 9,  9,  9,  0],
        [ 8, 13, 14,  0],
        [ 8,  3, 11,  0],
        ...,
        [ 5,  5,  9,  0],
        [ 1, 10, 10,  0],
        [15, 12, 12,  0]])
tensor([1, 1, 1,  ..., 1, 1, 1])
hierarchical [3.0, 3.0, 3.0]
tensor([[ 4,  2,  4,  0],
        [ 2,  6, 15,  0],
        [ 9,  5,  5,  0],
        ...,
        [ 6, 15,  3,  0],
        [ 9,  9,  9,  0],
        [ 2,  2,  4,  0]])
tensor([1, 1, 1,  ..., 1, 1, 1])
message length tensor([3, 3, 3,  ..., 3, 3, 3])
tensor([[ 4,  2,  4,  0],
        [ 2,  6, 15,  0],
        [ 9,  5,  5,  0],
        ...,
        [ 6, 15,  3,  0],
        [ 9,  9,  9,  0],
        [ 2,  2,  4,  0]])
tensor([1, 1, 1,  ..., 1, 1, 1])
hierarchical [3.0, 3.0, 3.0]
tensor([[ 6,  1,  3,  0],
        

###  symbol redundancy

In [12]:
for d in range(len(datasets)):
    
    attributes = n_attributes[d]
    values = n_values[d]
    vs_factor = int(paths[d][-2])
    vocab_size = (n_values[d] + 1) * vs_factor + 1
    
    for run in range(5): 
        
        path_to_run = paths[d] + str(setting) +'/' + str(run) + '/'
        #symbol_f = np.load(path_to_run + 'symbols_pernsame.npy')
        #path_to_interaction = (path_to_run + 'interactions/train/interactions_epoch' + str(n_epochs))
        path_to_interaction = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        interaction = torch.load(path_to_interaction)
        redundancy, MI = symbol_frequency(interaction, attributes, values, vocab_size)
        
        scores = {'symbol_redundancy': redundancy, 'MI_symbol-attribute_value': MI}
        
        pickle.dump(scores, open(path_to_run + 'symbol_redundancy.pkl', 'wb'))

c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:443: RuntimeWarning: invalid value encountered in divide
  return symbol_frequency / att_val_frequency, mutual_information
c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:443: RuntimeWarning: invalid value encountered in divide
  return symbol_frequency / att_val_frequency, mutual_information
c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:443: RuntimeWarning: invalid value encountered in divide
  return symbol_frequency / att_val_frequency, mutual_information
c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:443: RuntimeWarning: invalid value encountered in divide
  return symbol_frequency / att_val_frequency, mutual_information
c:\Users\rvver\Documents\CodeThesis\emergent-abstractions\utils\analysis_from_interaction.py:443: RuntimeWarning: invalid value encounte

###  compositionality scores: topsim, posdis, bosdis

In [13]:
# topsim
# although topsim values are stored throughout training if callbacks are verbose, we reevaluate the
# final topsim scores with more data points 

samples = 5000 # maybe shuffle from these because otherwise I just take the first 5,000 (which might not be the best)
for d, dataset in enumerate(datasets):
    
    dim = [n_values[d]]*n_attributes[d]
    
    for run in range(5):
        print("dataset", dataset, "run", run)
        
        topsim_final = {}
        path_to_run = paths[d] + str(setting) +'/' + str(run) + '/'
        path_to_interaction_train = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        path_to_interaction_val = (path_to_run + 'interactions/validation/epoch_' + str(n_epochs) + '/interaction_gpu0')
        
        TOPSIM = TopographicSimilarityConceptLevel(dim, is_gumbel=True)
        
        for mode in ['train', 'val']:

            if mode == 'train':
                interaction = torch.load(path_to_interaction_train)
            elif mode == 'val':
                interaction = torch.load(path_to_interaction_val)
                
                  
            messages = interaction.message.argmax(dim=-1)
            sender_input = interaction.sender_input
            n_targets = int(sender_input.shape[1]/2)
            # get target objects and fixed vectors to re-construct concepts
            target_objects = sender_input[:, :n_targets]
            target_objects = k_hot_to_attributes(target_objects, n_values[d])
            # concepts are defined by a list of target objects (here one sampled target object) and a fixed vector
            (objects, fixed) = retrieve_concepts_sampling(target_objects)
            # add one such that zero becomes an empty attribute for the calculation (_)
            objects = objects + 1
            concepts = torch.from_numpy(objects * (np.array(fixed)))
            specific_idx = np.where(np.sum(fixed, axis=1)==n_attributes[d])[0]
            messages_specific = messages[specific_idx]
            concepts_specific = concepts[specific_idx]
            
            generic_idx = np.where(np.sum(fixed, axis=1)==1)[0]
            messages_generic = messages[generic_idx]
            concepts_generic = concepts[generic_idx]

            messages = [msg.tolist() for msg in messages]
            messages_specific = [msg.tolist() for msg in messages_specific]
            messages_generic = [msg.tolist() for msg in messages_generic]

            encoded_input = encode_target_concepts_for_topsim(sender_input)
            # randomly take samples when more than 5000 samples are available
            # if len(encoded_input) > samples: 
            #     print("sampling")
            #     sample_indices = random.sample(range(len(encoded_input)), samples)
            #     sampled_input = [encoded_input[i] for i in sample_indices]
            #     sampled_messages = [messages[i] for i in sample_indices]
            #     print("start computing")
            #     print(len(sampled_input), len(sampled_input[0]), len(sampled_input[0][0]))
            #     topsim = TOPSIM.compute_topsim(sampled_input, sampled_messages)
            # else:
            topsim = TOPSIM.compute_topsim(encoded_input[0:samples], messages[0:samples]) # default: hausdorff distance for concepts, edit distance for messages
            # if len(concepts_specific) > samples:
            #     print("sampling specific")
            #     sample_indices_specific = random.sample(range(len(concepts_specific)), samples)
            #     sampled_input_specific = [concepts_specific[i] for i in sample_indices_specific]
            #     sampled_messages_specific = [messages_specific[i] for i in sample_indices_specific]
            #     topsim_specific = TOPSIM.compute_topsim(sampled_input_specific, sampled_messages_specific, 
            #                                             meaning_distance_fn="edit")
            # else:
            topsim_specific = TOPSIM.compute_topsim(concepts_specific[0:samples], messages_specific[0:samples], 
                                                        meaning_distance_fn="edit")
            
            topsim_generic = TOPSIM.compute_topsim(concepts_generic[0:samples], messages_generic[0:samples],
                                                   meaning_distance_fn="edit")

            print('... topsim computed')

            topsim_final['topsim_' + mode] = topsim
            topsim_final['topsim_specific_' + mode] = topsim_specific
            topsim_final['topsim_generic_' + mode] = topsim_generic
    
        pickle.dump(topsim_final, open(path_to_run +  "topsim_final.pkl", "wb" ) )
        print(topsim_final)        

dataset (3,4) run 0
... topsim computed
... topsim computed
{'topsim_train': 0.4053686848966944, 'topsim_specific_train': 0.46826182469130584, 'topsim_generic_train': 0.23631845246094896, 'topsim_val': 0.3871912617257834, 'topsim_specific_val': 0.4742402912865556, 'topsim_generic_val': 0.18310982757624067}
dataset (3,4) run 1
... topsim computed
... topsim computed
{'topsim_train': 0.3260413574320646, 'topsim_specific_train': 0.4240040807878953, 'topsim_generic_train': 0.256973882943923, 'topsim_val': 0.2989427130658574, 'topsim_specific_val': 0.40092034777108715, 'topsim_generic_val': 0.16646259657142157}
dataset (3,4) run 2
... topsim computed
... topsim computed
{'topsim_train': 0.31450582420267054, 'topsim_specific_train': 0.40003469906323014, 'topsim_generic_train': 0.1973183947562213, 'topsim_val': 0.30361565049139017, 'topsim_specific_val': 0.3834351702984578, 'topsim_generic_val': 0.13639342923640635}
dataset (3,4) run 3
... topsim computed
... topsim computed
{'topsim_train': 

In [14]:
# use Disent callback from egg

for d in range(len(datasets)): 
    
    path = paths[d]
    dim = [n_values[d]] * n_attributes[d]
    n_features = n_attributes[d] * n_values[d]
    vs_factor = int(path[-2])
    vocab_size = (n_values[d] + 1) * vs_factor + 1
    
    print("data set", dim)
    
    for run in range(5):
        
        posdis_bosdis = {}
    
        path_to_run = paths[d] + '/' + str(setting) +'/' + str(run) + '/'
        path_to_interaction_train = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        interaction = torch.load(path_to_interaction_train)
        
        messages = interaction.message.argmax(dim=-1)
        sender_input = interaction.sender_input
        n_targets = int(sender_input.shape[1]/2)
        # get target objects and fixed vectors to re-construct concepts
        target_objects = sender_input[:, :n_targets]
        target_objects = k_hot_to_attributes(target_objects, n_values[d])
        # concepts are defined by a list of target objects (here one sampled target object) and a fixed vector
        (objects, fixed) = retrieve_concepts_sampling(target_objects)
        # add one such that zero becomes an empty attribute for the calculation (_)
        objects = objects + 1
        concepts = torch.from_numpy(objects * (np.array(fixed)))

        # concrete/specific concepts: where all attributes are fixed
        concepts_specific = torch.tensor(
            objects[torch.sum(torch.from_numpy(fixed), dim=1) == n_attributes[d]])
        messages_specific = messages[torch.sum(torch.from_numpy(fixed), dim=1) == n_attributes[d]]

        # generic concepts: where only one attribute is fixed
        concepts_generic = torch.tensor(
            objects[torch.sum(torch.from_numpy(fixed), dim=1) == 1])
        messages_generic = messages[torch.sum(torch.from_numpy(fixed), dim=1) == 1]
        
        posdis_specific = Disent.posdis(concepts_specific, messages_specific)
        bosdis_specific = Disent.bosdis(concepts_specific, messages_specific, vocab_size)

        posdis_generic = Disent.posdis(concepts_generic, messages_generic)
        bosdis_generic = Disent.bosdis(concepts_generic, messages_generic, vocab_size)
        
        posdis = Disent.posdis(torch.from_numpy(objects), messages)
        bosdis = Disent.bosdis(torch.from_numpy(objects), messages, vocab_size)
        
        posdis_bosdis['posdis_specific'] = posdis_specific
        posdis_bosdis['bosdis_specific'] = bosdis_specific
        posdis_bosdis['posdis_generic'] = posdis_generic
        posdis_bosdis['bosdis_generic'] = bosdis_generic
        posdis_bosdis['posdis'] = posdis
        posdis_bosdis['bosdis'] = bosdis

        print(posdis_bosdis)
    
        pickle.dump(posdis_bosdis, open(path_to_run + "posdis_bosdis.pkl", "wb" ) )

data set [4, 4, 4]
{'posdis_specific': 0.09884431213140488, 'bosdis_specific': 0.21407409012317657, 'posdis_generic': 0.06809589266777039, 'bosdis_generic': 0.18087729811668396, 'posdis': 0.06690862029790878, 'bosdis': 0.18777218461036682}
{'posdis_specific': 0.03024621494114399, 'bosdis_specific': 0.2141767144203186, 'posdis_generic': 0.01766969822347164, 'bosdis_generic': 0.13220268487930298, 'posdis': 0.06220446154475212, 'bosdis': 0.1849241852760315}
{'posdis_specific': 0.03935683146119118, 'bosdis_specific': 0.16228920221328735, 'posdis_generic': 0.04953340068459511, 'bosdis_generic': 0.133585587143898, 'posdis': 0.03101786971092224, 'bosdis': 0.15981753170490265}
{'posdis_specific': 0.11684542894363403, 'bosdis_specific': 0.1782202571630478, 'posdis_generic': 0.022217100486159325, 'bosdis_generic': 0.1214355006814003, 'posdis': 0.1026143804192543, 'bosdis': 0.1469689905643463}
{'posdis_specific': 0.07545402646064758, 'bosdis_specific': 0.20166254043579102, 'posdis_generic': 0.076

In [4]:
# bosdis concept x context
for d in range(len(datasets)):

    vs_factor = int(paths[d][-2])
    vocab_size = (n_values[d] + 1) * vs_factor + 1
    
    for run in range(5):

        path_to_run = paths[d] + '/' + str(setting) +'/' + str(run) + '/' 
        path_to_interaction = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        interaction = torch.load(path_to_interaction)

        attributes = n_attributes[d]
        values = n_values[d]
        scores = bosdis(interaction, attributes, values, vocab_size)

        pickle.dump(scores, open(path_to_run + 'bosdis_scores.pkl', 'wb'))

In [5]:
# posdis concept x context
for d in range(len(datasets)):

    vs_factor = int(paths[d][-2])
    vocab_size = (n_values[d] + 1) * vs_factor + 1

    for run in range(5):
        path_to_run = paths[d] + '/' + str(setting) + '/' + str(run) + '/'
        print(path_to_run)
        path_to_interaction = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        #print(path_to_interaction)
        interaction = torch.load(path_to_interaction)

        attributes = n_attributes[d]
        values = n_values[d]
        scores = posdis(interaction, attributes, values, vocab_size)

        pickle.dump(scores, open(path_to_run + 'posdis_scores.pkl', 'wb'))

results/(3,4)_game_size_10_vsf_3//standard/0/
results/(3,4)_game_size_10_vsf_3//standard/1/
results/(3,4)_game_size_10_vsf_3//standard/2/
results/(3,4)_game_size_10_vsf_3//standard/3/
results/(3,4)_game_size_10_vsf_3//standard/4/


### co-occurrences

In [ ]:
# Not yet implemented:

for d in range(len(datasets)):
    
    vs_factor = int(paths[d][-2])
    
    for run in range(5): 
        
        path_to_run = paths[d] + str(setting) +'/' + str(run) + '/'
        path_to_interaction = (path_to_run + 'interactions/train/epoch_' + str(n_epochs) + '/interaction_gpu0')
        interaction = torch.load(path_to_interaction)

        attributes = n_attributes[d]
        values = n_values[d]
        
        scores = cooccurrence_per_hierarchy_level(interaction, attributes, values, vs_factor)

        print(scores)
        
        pickle.dump(scores, open(path_to_run + 'normalized_cooccurrence.pkl', 'wb'))
    